include gruvbox_dark.conf

enable_audio_bell no
font_family      Iosevka
bold_font        bold Iosevka
italic_font      italic Iosevka
bold_italic_font bold_italic Iosevka
font_size 16.0

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard


